import LegalPage from "@/components/LegalPage";

export default function PoliticaDePrivacidadePage() {
  return <LegalPage title="Política de Privacidade" description="Entenda como a Moda Run coleta, usa, protege e compartilha dados no app de comunidade, treinos, eventos e loja." updatedAt="03/05/2026" sections={[
    { title: "1. Quem somos", body: ["A Moda Run é uma plataforma voltada para corredores, com recursos de comunidade, criação de treinos, eventos, loja, chat e notificações. Esta política explica como tratamos dados pessoais de usuários do site e app.", "Ao usar a Moda Run, você declara que leu esta política e concorda com o tratamento de dados necessário para funcionamento da plataforma."] },
    { title: "2. Dados que podemos coletar", body: ["Podemos coletar dados de cadastro, como nome, e-mail, foto de perfil, cidade, estado e preferências de corrida.", "Também podemos tratar conteúdos publicados pelo usuário, comentários, curtidas, seguidores, mensagens privadas, eventos salvos, treinos criados, participação em treinos, preferências de cidade, interações com notificações e registros técnicos de acesso.", "No caso da loja, podemos usar dados informados voluntariamente para facilitar atendimento, interesse em produtos e direcionamento para WhatsApp."] },
    { title: "3. Finalidades de uso", body: ["Usamos os dados para autenticar usuários, manter perfis, exibir publicações, permitir comentários, curtidas, seguidores, chat privado, notificações, criação de treinos, sugestão de eventos e funcionamento da loja.", "Também podemos usar dados agregados para melhorar a experiência, prevenir abuso, segurança, suporte e desenvolvimento de novas funcionalidades."] },
    { title: "4. Base legal", body: ["O tratamento pode ocorrer para execução dos serviços solicitados pelo usuário, cumprimento de obrigações legais, legítimo interesse da plataforma, prevenção a fraudes e, quando necessário, consentimento do usuário."] },
    { title: "5. Conteúdo público e privado", body: ["Publicações no feed, nome, foto de perfil, seguidores, seguindo e treinos públicos podem ser visíveis a outros usuários conforme a funcionalidade usada.", "Mensagens privadas são destinadas aos participantes da conversa, mas podem ser preservadas em banco para segurança, auditoria, prevenção de abuso e cumprimento de obrigações legais."] },
    { title: "6. Compartilhamento", body: ["Não vendemos dados pessoais. Podemos compartilhar dados com provedores necessários para operação técnica, como hospedagem, autenticação, banco de dados, armazenamento, análise técnica e atendimento.", "Também podemos compartilhar informações quando exigido por lei, autoridade competente ou para proteger direitos, segurança e integridade da plataforma."] },
    { title: "7. Segurança", body: ["Adotamos medidas técnicas e organizacionais razoáveis para proteger os dados, como autenticação, permissões, políticas de acesso e uso de provedores confiáveis.", "Nenhum sistema é absolutamente imune a incidentes. Caso identifiquemos risco relevante, adotaremos medidas proporcionais conforme a legislação aplicável."] },
    { title: "8. Direitos do titular", body: ["Você pode solicitar acesso, correção, atualização, exclusão, portabilidade, informação sobre compartilhamento e revisão de tratamentos aplicáveis, conforme a legislação vigente.", "Para exercer seus direitos, use a página de contato ou a página de exclusão de conta."] },
    { title: "9. Crianças e adolescentes", body: ["A Moda Run não é direcionada a crianças. Usuários menores de idade devem utilizar a plataforma com autorização e supervisão de responsável legal."] },
    { title: "10. Alterações", body: ["Esta política pode ser atualizada para refletir mudanças legais, técnicas ou funcionais. A data de atualização será indicada no topo da página."] },
  ]} />;
}
